# Basics of Julia

## Variables, comments and expressions

Defining a new variable is straightforward:

In [1]:
foo = 1

1

You can assign multiple variables in the same line:

In [2]:
a, b, c = 1, 2, 3
# a = 1; b = 2; c = 3

(1, 2, 3)

In [3]:
#= This comment
spans multiple
lines
=#

By default, each statement takes up a single line

In [4]:
a = 1
a += 1 # a = a + 1
a *= 2 # a = a * 2

4

But we can use ';' to chain multiple statements in a single line

In [5]:
a = 1; a += 1; a *= 2

4

Statements can also be put inside a block. The difference is that a block can define a scope.

In [6]:
begin
    a = 1
    a += 1
    a *= 2
end

4

## Elementary types

Integers,

In [7]:
a = 1

1

Floats,

In [8]:
b = 0.2

0.2

Booleans

In [9]:
e = true; f = false

false

Characters,

In [10]:
c = 'c'

'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)

Strings

In [11]:
d = "Hello, world\n" # NB C-style character literals work

"Hello, world\n"

In [12]:
print(d)

Hello, world


Arrays

In [13]:
x = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

Tuples

In [14]:
y = ("Waffle", 2)

("Waffle", 2)

Dictionaries

In [15]:
z = Dict(
    "Frites" => 2.0,
    "Fricandelle" => 1.5,
    "Sauce Andalouse" => 0.3,
)

Dict{String, Float64} with 3 entries:
  "Frites"          => 2.0
  "Fricandelle"     => 1.5
  "Sauce Andalouse" => 0.3

## Conditional expressions

Conditionals are built from `if`/`elseif`/`else` clauses

In [16]:
# get a random number between -30 and 150
water_temperature = rand(-30:150)
println("The water temperature is $water_temperature degrees Celsius")
if water_temperature < 0
    print("Ice")
elseif water_temperature < 100
    print("Liquid Water")
else
    print("Steam")
end

The water temperature is 63 degrees Celsius
Liquid Water

Note that conditionals are expressions that return a value

In [17]:
age = rand(1:40)
println("My age is $age")
status = if age < 18
    "minor"
else
    "adult"
end

My age is 31


"adult"

We can rewrite the above more compactly using the *ternary operator*

In [18]:
status = age < 18 ? "minor" : "adult"

"adult"

## Loops

For loops are like in Python. They iterate over an object

In [19]:
k = 0
for i in 1:10
    k += i
end
k

55

In [20]:
n = 10
while n != 1
    println(n)
    n = iseven(n) ? div(n,2) : 3*n+1
end
println(n)

10
5
16
8
4
2
1


### Nested for-loops
It's quite common to write multiple nested for-loops, which tends to become hard to read

In [21]:
for i in 1:5
    for j in 1:3
        print(i+j, " ")
    end
end

2 3 4 3 4 5 4 5 6 5 6 7 6 7 8 

So there's a special syntax for that:

In [22]:
for i in 1:5, j in 1:3
    print(i+j, " ")
end

2 3 4 3 4 5 4 5 6 5 6 7 6 7 8 

## Arrays

Arrays are the main collection in Julia. They can be of any dimension, and hold items of a single, arbitrary type

In [23]:
# a 1 dimensional vector with 10 elements of type 'double'
a = Vector{Float64}(undef, 10)

10-element Vector{Float64}:
 2.0e-323
 4.0e-323
 1.5e-323
 1.6e-322
 6.9527732814254e-310
 4.94e-322
 4.94e-321
 1.235e-321
 1.0e-322
 6.94042323817465e-310

In [24]:
# equivalent to previous line
b = Array{Float64,1}(undef, 10)

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [25]:
# A 2 dimensional array of integers with 3 rows and 4 columns
c = Array{Int,2}(undef, 3,4)

3×4 Matrix{Int64}:
 0  0  0  0
 0  0  0  0
 0  0  0  0

In [26]:
d = Array{Int,2}(undef, (3,4))

3×4 Matrix{Int64}:
 140475633093648  140475499638880  140475633094320  140475499638880
 140475499638880  140475633093664  140475602639760  140475499630704
 140475499630704  140475499636720  140475633094384  140475499638880

There's also special constructors for arrays of the same value

In [27]:
e = zeros(3,4)

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [28]:
f = ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [29]:
g = fill("Hello", 4)

4-element Vector{String}:
 "Hello"
 "Hello"
 "Hello"
 "Hello"

### Explicit enumeration

A comma separated list gives a vector

In [30]:
a = [1,2,3,4] # 1D array (column vector)

4-element Vector{Int64}:
 1
 2
 3
 4

whereas omitting the commas returns a row vector

In [31]:
b = [1 2 3 4] # 1 x 4 matrix (row vector)

1×4 Matrix{Int64}:
 1  2  3  4

In [32]:
c = [1 2; 3 4; 5 6] # 3 x 2 matrix

3×2 Matrix{Int64}:
 1  2
 3  4
 5  6

In [33]:
d = [1; 2;; 3; 4;;; 5; 6;; 7; 8] # 2 x 2 x 2 3D array

2×2×2 Array{Int64, 3}:
[:, :, 1] =
 1  3
 2  4

[:, :, 2] =
 5  7
 6  8

### Ranges
Since it's very common to work with ranges of values, there's a special syntax for those (it works exactly like in Matlab)

In [34]:
i = 1:10 # integers from 1 to 10

1:10

In [35]:
x = 0.0:0.01:1.0 # from 0.0 to 1.0 by steps of 0.1

0.0:0.01:1.0

If you just want `n` numbers between two values, there's also `LinRange`

In [36]:
y = LinRange(0.0,1.0,100)

100-element LinRange{Float64, Int64}:
 0.0, 0.010101, 0.020202, 0.030303, …, 0.969697, 0.979798, 0.989899, 1.0

The one difference between ranges in Julia and those in Python/Matlab, is that they aren't arrays! Instead, the elements are generated on demand when iterating over them. You can use the `collect` function to obtain a vector of the elements of an iterator.

In [37]:
collect(i)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

### Array comprehensions
We can also construct more complex arrays using comprehensions

In [38]:
# Apply arbitrary function to a collection
a = [i^2 for i in 1:10]

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [39]:
# Use multiple indices to generate higher dimensional arrays
b = [i+j for i in 1:5, j in 1:5]

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [40]:
# Filter elements using a condition
c = [i/(i^2) for i in 1:10 if iseven(i)]

5-element Vector{Float64}:
 0.5
 0.25
 0.16666666666666666
 0.125
 0.1

Comprehensions can also be passed directly to functions taking an iterator, like `sum`. In this case, no memory is allocated for the elements. They just get summed one-by-one.

In [41]:
# special syntax for functions taking a collection
p = 4 * sum((-1)^k / (2k+1) for k in 0:10000)

3.1416926435905346

## Array indexing

In [42]:
# default arrays start at 1
a[1]

1

In [43]:
# use an array of indices
a[[1,3,5]]

3-element Vector{Int64}:
  1
  9
 25

In [44]:
# ranges work too
a[1:5]

5-element Vector{Int64}:
  1
  4
  9
 16
 25

In [45]:
b[1,:] # first row of b

5-element Vector{Int64}:
 2
 3
 4
 5
 6

In [46]:
b[:,2] # second column of b

5-element Vector{Int64}:
 3
 4
 5
 6
 7

Default arrays have their indices start at one. This isn't always the case however, and there are many special array types that don't. For this reason, you should always be careful when indexing arbitrary arrays

In [47]:
a[begin], # first element
a[end] # last element

(1, 100)

For instance, this is the recommended way to iterate over a collection's indices

In [48]:
for i in eachindex(a)
    print(a[i], " ")
end

1 4 9 16 25 36 49 64 81 100 

Likewise, for multidimensional arrays, the `axes` function will produce the indices of a given dimension

In [49]:
# iterate over each column of b
for j in axes(b,2)
    println(b[:,j])
end

[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]
[6, 7, 8, 9, 10]


## Broadcasting

Calling functions works just as expected

In [50]:
cos(π/2) # NB. use "\pi<TAB>" for unicode π

6.123233995736766e-17

Since it's common to call a function on each element of a collection, there's a special syntax for *vectorizing* a function call. This is called *broadcasting*.

In [51]:
xs = LinRange(0.0,2π,10)
cos.(xs)

10-element Vector{Float64}:
  1.0
  0.766044443118978
  0.17364817766693041
 -0.4999999999999998
 -0.9396926207859083
 -0.9396926207859084
 -0.5000000000000004
  0.17364817766692997
  0.7660444431189778
  1.0

In [52]:
# equivalent to
[cos(x) for x in xs]

10-element Vector{Float64}:
  1.0
  0.766044443118978
  0.17364817766693041
 -0.4999999999999998
 -0.9396926207859083
 -0.9396926207859084
 -0.5000000000000004
  0.17364817766692997
  0.7660444431189778
  1.0

In [53]:
# It also applies to infix operators
xs .* cos.(xs)

10-element Vector{Float64}:
  0.0
  0.5347999099613034
  0.24245859523008167
 -1.0471975511965972
 -2.624116830305377
 -3.2801460378817215
 -2.094395102393197
  0.8486050833052836
  4.278399279690426
  6.283185307179586

Broadcasting applies to pretty much every operation in Julia, including assignment

In [54]:
a = zeros(5)

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [55]:
a .= [1,2,3,4,5] # NB. without the dot, this would create a new array

5-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0

In [56]:
a .+= 1.0

5-element Vector{Float64}:
 2.0
 3.0
 4.0
 5.0
 6.0

In [57]:
a .+= [6,7,8,9,10]

5-element Vector{Float64}:
  8.0
 10.0
 12.0
 14.0
 16.0

When chaining multiple broadcasted calls in the same statement, they get fused into a single loop

In [58]:
a .= 1:5
a .= a.^3 .- a.^2 .+ a .- 1

5-element Vector{Float64}:
   0.0
   5.0
  20.0
  51.0
 104.0

In [59]:
# equivalent to
a .= 1:5
for i in eachindex(a)
    a[i] = a[i]^3 - a[i]^2 + a[i] - 1
end
a

5-element Vector{Float64}:
   0.0
   5.0
  20.0
  51.0
 104.0

In [60]:
a .= 1:5
# short-hand
@. a = a^3 - a^2 + a - 1

5-element Vector{Float64}:
   0.0
   5.0
  20.0
  51.0
 104.0

## Functions

Defining a new function is done as follows

In [61]:
function collatz(n)
    if iseven(n)
        return div(n,2)
    else
        return 3n+1
    end
end

collatz (generic function with 1 method)

Recall that we can replace the `if` by the ternary operator

In [62]:
function collatz(n)
    return iseven(n) ? div(n,2) : 3n+1
end

collatz (generic function with 1 method)

In fact, we don't even need the `return` in this case. By default, functions return the value of their last statement.

In [63]:
# implicit return
function collatz(n)
    iseven(n) ? div(n,2) : 3n+1
end

collatz (generic function with 1 method)

We can also define simple functions in a single line. This is very useful for math.

In [64]:
# inline definition
square(x) = x^2

square (generic function with 1 method)

Additionally, we can also create "anonymous" functions and assign them (or not) to variables

In [65]:
# Lambda expression
square_2 = x -> x^2

#23 (generic function with 1 method)

In [66]:
square_3 = function(x)
    x^2
end

#25 (generic function with 1 method)

## Default values and Keyword arguments

Finally, when defining a function, we can specify default values for its arguments, as well as keyword arguments.

In [67]:
function say_hello(x = "World"; hello_str="Hello", end_str="!")
    # NB. '*' concatenates strings
    println(hello_str * ", " * x * end_str)
end

say_hello (generic function with 2 methods)

Calling the function without arguments will use the default values

In [68]:
say_hello()

Hello, World!


If we pass in an argument, it gets used instead of the default

In [69]:
say_hello("Alice")

Hello, Alice!


Keyword arguments work a bit differently. We have to assign them by name, and this can be done in any order

In [70]:
say_hello("Alice", hello_str="Bonjour", end_str="?")

Bonjour, Alice?


In [71]:
say_hello("Alice", end_str="", hello_str="Ciao")

Ciao, Alice
